# Spring Boot
spring.application.name=purchase-transaction-api
server.port=8080

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:purchasedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (para debug)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Spring Data JDBC (sem JPA)
spring.sql.init.mode=always
spring.sql.init.data-locations=optional:classpath:data.sql

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true

# Logging
logging.level.root=INFO
logging.level.com.wex.finance=DEBUG

# Treasury API currency mapping
wex.treasury.currency-name-mapping.BRL=Real
wex.treasury.currency-name-mapping.EUR=Euro
wex.treasury.currency-name-mapping.JPY=Yen
wex.treasury.currency-name-mapping.GBP=Pound
wex.treasury.currency-name-mapping.CAD=Dollar
wex.treasury.currency-name-mapping.AUD=Dollar
wex.treasury.currency-name-mapping.CHF=Franc
